### PR TITLE
Fixes #14 - Add dependency for Jacrys.DateTimeExtensions

### LINKED ISSUE #14: Add epoch converter
Add a handler to convert epoch times to Date Time values.

### PR DESCRIPTION
**Pull request by jacrys**
Added dependency to convert Double or Long epoch times to DateTime values.

### CODE REVIEW

**Comment by jacrys** [comment]
Fixes #14

**Comment by jacrys** [comment]
@devsgarage @OnyxPrime

**Review by devsgarage — APPROVED** [review]
Thank you for contributing and creating the package to solve our datetime conversion issue. We'll pull it in and look at using it.

**Review by devsgarage — COMMENTED** [review]
Extension methods are there, but are inaccessible due to their access modifier. Please make them public and republish to NuGet.

**Pull request merged**
